apiVersion: v1
kind: Secret
metadata:
  name: mini-fintickstreams-secrets
type: Opaque
stringData:
  SHARD_MAIN_DSN: "postgresql://USER:PASSWORD@pg-postgresql:5432/DBNAME?sslmode=disable"
  REDIS_NODE_A: "redis://redis:6379"
